#!/bin/bash

# Sets packet loss for all outgoing IP packets
# and destination port DPORT

# network interface, can be obtained with ifconfig
INT=wlo1 
DPORT=4433
# DPORT mask, set to 0x0 to affect all ports
MASK=0xffff
LOSS=10%

tc qdisc add    \
    dev $INT    \
    root        \
    handle 1:0  \
    prio

tc filter add                           \
    dev $INT                            \
    protocol ip                         \
    parent 1:0                          \
    prio 1                              \
    u32 match ip dport $DPORT $MASK     \
    class 1:1

tc qdisc add    \
    dev $INT    \
    parent 1:1  \
    handle 10:0 \
    netem loss \
    $LOSS
